# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    metallb-config.yaml                                :+:    :+:             #
#                                                      +:+                     #
#    By: nkuipers <nkuipers@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/11/11 15:29:48 by nkuipers      #+#    #+#                  #
#    Updated: 2020/11/11 15:29:50 by nkuipers      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: ip-pools
        protocol: layer2
        addresses:
          - 192.168.99.230-192.168.99.240
