# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Dockerfile                                         :+:    :+:             #
#                                                      +:+                     #
#    By: nkuipers <nkuipers@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/11/25 13:18:39 by nkuipers      #+#    #+#                  #
#    Updated: 2020/11/25 14:08:14 by nkuipers      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest
RUN apk update
RUN apk upgrade
RUN apk add nginx

EXPOSE 80 443 22
